BoiNiyeOvijan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('sreed/', include('sreed.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

sreed/urls.py
from django.urls import path
from . import views

app_name = 'sreed'
urlpatterns = [
    path('', views.sreedConf, name='sreedConf'),
    # path('<int:blog_id>/', views.detail, name='detail'),
]

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=800)
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

sreed/models.py
from django.db import models

# Create your models here.


class TextLevel(models.Model):
    title = models.CharField(max_length=50)
    words = models.TextField(max_length=1200)
    date = models.DateField()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
# Create your views here.


def all_blogs(request):
    blog_count = Blog.objects.count()
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs, 'blog_count': blog_count})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

sreed/views.py
from django.shortcuts import render
from .models import TextLevel
# Create your views here.


def sreedConf(request):
    return render(request, 'sreed/sreedConf.html',)

blog/templates/blog/all_blogs.html
{% extends 'portfolio\base.html' %}
{% block content %}
<h1>All Blogs</h1>
<h2>Nick has written {{ blog_count }} blog{{ blog_count|pluralize }}</h2>
{% for blog in blogs %}
<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<p>{{ blog.description|safe|truncatechars:100 }}</p>
<!-- <p>{{ blog.description|striptags|truncatechars:100 }}</p> -->
<h5>{{ blog.date|date:'M d Y' }}</h5>
{% endfor %}
{% endblock %}

blog/templates/blog/detail.html
<h1>{{blog.title}}</h1>
<h2>--{{ blog.date|date:'F jS Y' }}--</h2>
{{ blog.description|safe }}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Boi Niye Ovijan</title>
  <link rel="stylesheet" href="{% static 'portfolio/styleBase.css' %}">
  <link rel="stylesheet" href="{% static 'portfolio/styleHome.css' %}">
  <link rel="stylesheet" href="{% static 'sreed/styleSreed.css' %}">
  <link href="{% static 'portfolio/fontawesome-free-5.15.3-web/css/all.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link
    href="https://fonts.googleapis.com/css2?family=Girassol&family=Newsreader:wght@300&family=Roboto+Condensed:wght@300&display=swap"
    rel="stylesheet">
</head>
<body>
  <!-- this is for the navigation bar -->
  <div class="navBar">
    <header>
      <div class="wrapper">
      <div class="logo">
        <a href="#"><img src="{% static 'portfolio/logo134.png' %}" alt="logo"></a>
      </div>
    <nav>
      <a href="{% url 'home' %}">home</a>
      <a href="#">about</a>
      <a href="{% url 'blog:all_blogs' %}">blogs</a>
      <a href="#">contact</a>
      <div class="dropdown">
        <a href="">training</a>
        <i class="fas fa-chevron-down"></i>
        <div class="dropdown-content">
          <a href="#">WPM</a>
          <a href="#">Eye</a>
          <a href="{% url 'sreed:sreedConf' %}">Speed</a>
        </div>
    </nav>
  </div>
  </header>
  </div>

  {% block content %} {% endblock %}

  <!-- This is the footer for every page -->
  <div class="footer">
    <div class="footerPic">
      <a href="" class='footerIcon'>
        <i class="fab fa-facebook-square"></i>
      </a>
      <a href="" class='footerIcon'>
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class='footerIcon'>
        <i class="fas fa-envelope"></i>
      </a>
      <a href="" class='footerIcon'>
        <i class="fab fa-github-square"></i>
      </a>
    </div>
  </div>
</body>
</html>

sreed/templates/sreed/sreedConf.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<!-- this is for the banner -->
<div class="sreedBanner" id="sreedBanner">
  <div class="sreedImgban" id="sreedImgban4">
    <div class="sreedImgbanBox" id="sreedImgbanBox1">
      <p>The average college student can read 250 words per minute</p>
    </div>
    <div class="sreedImgbanBox" id="sreedImgbanBox2">
      <p>A good reader can read 400 words per minute</p>
    </div>
    <div class="sreedImgbanBox" id="sreedImgbanBox3">
      <p>An average novel contains 120,000 words</p>
    </div>
    <div class="sreedImgbanBox" id="sreedImgbanBox4">
      <p>Spend less time and acquire more</p>
    </div>
  </div>
</div>
<script>
  var imgbanStatus = 1;
    var imgbanTimer = 4000;
    window.onload = function () {
      imgbanLoop();
    }
    var startimgbanLoop = setInterval(function () {
      imgbanLoop();
    }, imgbanTimer);
    document.getElementById("sreedBanner").onmouseenter = function () {
      clearInterval(startimgbanLoop);
    }
    document.getElementById("sreedBanner").onmouseleave = function () {
      startimgbanLoop = setInterval(function () {
        imgbanLoop();
      }, imgbanTimer);
    }

    function imgbanLoop() {
      if (imgbanStatus === 1) {
        document.getElementById("sreedImgbanBox1").style.opacity = "1";
        document.getElementById("sreedImgbanBox2").style.opacity = "0";
        document.getElementById("sreedImgbanBox3").style.opacity = "0";
        document.getElementById("sreedImgbanBox4").style.opacity = "0";

        setTimeout(function () {
          document.getElementById("sreedImgbanBox1").style.opacity = "0";
        }, 3000)
        imgbanStatus = 2;
      }
      else if (imgbanStatus === 2) {
        document.getElementById("sreedImgbanBox1").style.opacity = "0";
        document.getElementById("sreedImgbanBox2").style.opacity = "1";
        document.getElementById("sreedImgbanBox3").style.opacity = "0";
        document.getElementById("sreedImgbanBox4").style.opacity = "0";

        setTimeout(function () {
          document.getElementById("sreedImgbanBox2").style.opacity = "0";
        }, 3000)
        imgbanStatus = 3;
      }
      else if (imgbanStatus === 3) {
        document.getElementById("sreedImgbanBox1").style.opacity = "0";
        document.getElementById("sreedImgbanBox2").style.opacity = "0";
        document.getElementById("sreedImgbanBox3").style.opacity = "1";
        document.getElementById("sreedImgbanBox4").style.opacity = "0";

        setTimeout(function () {
          document.getElementById("sreedImgbanBox3").style.opacity = "0";
        }, 3000)
        imgbanStatus = 4;
      }
      else if (imgbanStatus === 4) {
        document.getElementById("sreedImgbanBox1").style.opacity = "0";
        document.getElementById("sreedImgbanBox2").style.opacity = "0";
        document.getElementById("sreedImgbanBox3").style.opacity = "0";
        document.getElementById("sreedImgbanBox4").style.opacity = "1";

        setTimeout(function () {
          document.getElementById("sreedImgbanBox4").style.opacity = "0";
        }, 3000)
        imgbanStatus = 1;
      }
    }
</script>
<br>
<!-- From here this will be rest of the page -->
<div class="howToTrain">
  <div class="howToTrainHeading">
    <h1>How To Train For Speed Reading</h1>
  </div>
  <p class="howToTrainPara">To train yourself use this page every day. Start with a constant word per minute from 100 to 500 (like 200 wpm is the average reader's speed).Train each day with one level of text (starting from level 1). Select how many Words At a Time to read (start from 1 word and go for 3 words eventually). When you feel confortable with current settings increase Words At a Time then Level of Text and finally Words Per Minute </p>
</div>
<br>
<div class="selection">
  <h2>Selection Pane</h2>
  <form action="">
    <label for="level">Text Level</label>
    <select name="textLevel" id="level">
      <!-- Here will be a for loop for available text level -->
    </select>
    <br>
    <label for="wpm">Words Per Minute (100-500)</label>
    <input id="wpm" type="number" placeholder="Put any integer">
    <br>
    <div class="wordSelection">
      <label for="wordSelect">Select Word/Words At A Time</label>
      <br>
      <input type="checkbox" name="oneWord" id="wordSelect" class='wordSelect'>One Word</input>
      <input type="checkbox" name="twoWords" id="wordSelect" class='wordSelect'>Two Words</input>
      <input type="checkbox" name="threeWords" id="wordSelect" class='wordSelect'>Three Words</input>
    </div>
    <button id="submit">Submit</button>
  </form>
</div>
{% endblock %}